name: tests-workflow
run-name: tests-workflow-runner

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker/docker-compose.test.yml --env-file .env.test up -d

      - name: run tests
        run: |
          docker exec cuecards-node-test npm run test

      - name: stop docker containers and quit
        run: |
          docker stop $(docker ps -aq)
